services:
  client:
    image: macdent-ai-client-development
    build:
      context: .
      dockerfile: ./build/development/client/Dockerfile
    volumes:
      - .:/app
    networks:
      - ai-chatbot

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai-chatbot

networks:
  ai-chatbot:
    driver: bridge

volumes:
  qdrant_data:
      driver: local